<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\HMS.Essentials.TestBase\HMS.Essentials.TestBase.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HMS.Essentials.AspNetCore</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HMS.Essentials.AspNetCore\HMS.Essentials.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\HMS.Essentials.Core\HMS.Essentials.Core.csproj" />
  </ItemGroup>

</Project>
