<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\HMS.Essentials.TestBase\HMS.Essentials.TestBase.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HMS.Essentials.MediatR.DomainEvents.Tests</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HMS.Essentials.MediatR.DomainEvents\HMS.Essentials.MediatR.DomainEvents.csproj" />
  </ItemGroup>

</Project>
